// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhachSan.Data;

#nullable disable

namespace QuanLyKhachSan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260627053213_AddKhuVucApDungToVoucher")]
    partial class AddKhuVucApDungToVoucher
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKhachSan.Models.CaLamViec", b =>
                {
                    b.Property<int>("MaCa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCa"));

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenCa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaCa");

                    b.ToTable("CaLamViec");

                    b.HasData(
                        new
                        {
                            MaCa = 1,
                            GioBatDau = new TimeSpan(0, 6, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 14, 0, 0, 0),
                            MoTa = "Lễ tân và phục vụ buổi sáng",
                            TenCa = "Ca Sáng"
                        },
                        new
                        {
                            MaCa = 2,
                            GioBatDau = new TimeSpan(0, 14, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 22, 0, 0, 0),
                            MoTa = "Lễ tân và phục vụ buổi chiều tối",
                            TenCa = "Ca Chiều"
                        },
                        new
                        {
                            MaCa = 3,
                            GioBatDau = new TimeSpan(0, 22, 0, 0, 0),
                            GioKetThuc = new TimeSpan(0, 6, 0, 0, 0),
                            MoTa = "Trực đêm và bảo vệ",
                            TenCa = "Ca Đêm"
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.ChamCong", b =>
                {
                    b.Property<int>("MaCC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCC"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("GioRa")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("GioVao")
                        .HasColumnType("time");

                    b.Property<int?>("MaLich")
                        .HasColumnType("int");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCC")
                        .HasColumnType("date");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaCC");

                    b.HasIndex("MaLich");

                    b.HasIndex("MaNV");

                    b.ToTable("ChamCong");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDG"));

                    b.Property<int?>("MaDP")
                        .HasColumnType("int");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("MaDG");

                    b.HasIndex("MaDP");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaLoai");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DanhGiaNhanVien", b =>
                {
                    b.Property<int>("MaDGNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDGNV"));

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("MaDGNV");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaNV");

                    b.ToTable("DanhGiaNhanVien");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DatPhong", b =>
                {
                    b.Property<int>("MaDP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDP"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCheckOut")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguonDat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaDP");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaPhong");

                    b.ToTable("DatPhong");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DichVu", b =>
                {
                    b.Property<int>("MaDV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDV"));

                    b.Property<decimal>("GiaDV")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("TenDV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDV");

                    b.ToTable("DichVu");

                    b.HasData(
                        new
                        {
                            MaDV = 1,
                            GiaDV = 15000m,
                            TenDV = "Nước suối"
                        },
                        new
                        {
                            MaDV = 2,
                            GiaDV = 25000m,
                            TenDV = "Bò húc"
                        },
                        new
                        {
                            MaDV = 3,
                            GiaDV = 55000m,
                            TenDV = "Mì xào hải sản"
                        },
                        new
                        {
                            MaDV = 4,
                            GiaDV = 300000m,
                            TenDV = "Spa Toàn Thân"
                        },
                        new
                        {
                            MaDV = 5,
                            GiaDV = 50000m,
                            TenDV = "Giặt là cao cấp"
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHD"));

                    b.Property<decimal>("GiamGiaThanhVien")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("MaDP")
                        .HasColumnType("int");

                    b.Property<int?>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLanhToan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienDichVu")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("TienPhong")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("MaHD");

                    b.HasIndex("MaDP");

                    b.HasIndex("MaNV");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HangThanhVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaTK")
                        .HasColumnType("int");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaKH");

                    b.HasIndex("MaTK")
                        .IsUnique()
                        .HasFilter("[MaTK] IS NOT NULL");

                    b.ToTable("KhachHang");

                    b.HasData(
                        new
                        {
                            MaKH = 1,
                            CCCD = "045612378945",
                            DiemTichLuy = 0,
                            Email = "ltd@gmail.com",
                            HangThanhVien = "Đồng",
                            HoTen = "Lê Thị D",
                            SDT = "0933456789"
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.LichLamViec", b =>
                {
                    b.Property<int>("MaLich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLich"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaCa")
                        .HasColumnType("int");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLam")
                        .HasColumnType("date");

                    b.HasKey("MaLich");

                    b.HasIndex("MaCa");

                    b.HasIndex("MaNV");

                    b.ToTable("LichLamViec");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.LoaiPhong", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<decimal>("GiaPhong")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KhuVuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SoNguoiToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TienNghi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TuKhoa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiPhong");

                    b.HasData(
                        new
                        {
                            MaLoai = 1,
                            GiaPhong = 300000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Hồ Chí Minh",
                            SoNguoiToiDa = 1,
                            TenLoai = "Phòng Đơn Tiêu Chuẩn",
                            TienNghi = "Tivi, Máy Lạnh, Cửa Sổ Nhỏ",
                            TuKhoa = "thành phố, phố, trung tâm, sài gòn"
                        },
                        new
                        {
                            MaLoai = 2,
                            GiaPhong = 500000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Hồ Chí Minh",
                            SoNguoiToiDa = 2,
                            TenLoai = "Phòng Đôi Tiêu Chuẩn",
                            TienNghi = "Tivi, Tủ Lạnh, Cửa Sổ Hướng Phố",
                            TuKhoa = "thành phố, phố, trung tâm, sài gòn"
                        },
                        new
                        {
                            MaLoai = 3,
                            GiaPhong = 1200000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Hồ Chí Minh",
                            SoNguoiToiDa = 2,
                            TenLoai = "Phòng VIP Hướng Biển",
                            TienNghi = "Tivi OLED, Bồn tắm, Ban công siêu rộng, View Biển trực tiếp",
                            TuKhoa = "biển, resort, nghỉ dưỡng"
                        },
                        new
                        {
                            MaLoai = 4,
                            GiaPhong = 850000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Hồ Chí Minh",
                            SoNguoiToiDa = 4,
                            TenLoai = "Phòng Gia Đình",
                            TienNghi = "2 Giường Đôi cỡ lớn, Không gian sinh hoạt, Trò chơi điện tử",
                            TuKhoa = "gia đình, rộng"
                        },
                        new
                        {
                            MaLoai = 5,
                            GiaPhong = 600000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Phan Thiết",
                            SoNguoiToiDa = 2,
                            TenLoai = "Phòng Biển Standard",
                            TienNghi = "View biển, Máy lạnh, Tivi, Ban công",
                            TuKhoa = "biển, beach, phan thiết, nghỉ dưỡng"
                        },
                        new
                        {
                            MaLoai = 6,
                            GiaPhong = 900000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Phan Thiết",
                            SoNguoiToiDa = 2,
                            TenLoai = "Phòng Biển Deluxe",
                            TienNghi = "View biển trực diện, Bồn tắm, Ban công rộng, Minibar",
                            TuKhoa = "biển, beach, phan thiết, view"
                        },
                        new
                        {
                            MaLoai = 7,
                            GiaPhong = 1500000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Phan Thiết",
                            SoNguoiToiDa = 3,
                            TenLoai = "Phòng Biển Suite",
                            TienNghi = "View biển panorama, Phòng khách riêng, Jacuzzi",
                            TuKhoa = "biển, beach, phan thiết, suite"
                        },
                        new
                        {
                            MaLoai = 8,
                            GiaPhong = 1200000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Phan Thiết",
                            SoNguoiToiDa = 5,
                            TenLoai = "Phòng Biển Gia Đình",
                            TienNghi = "2 Phòng ngủ, View biển, Bếp nhỏ, Sân vườn riêng",
                            TuKhoa = "biển, beach, phan thiết, gia đình"
                        },
                        new
                        {
                            MaLoai = 9,
                            GiaPhong = 2500000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Phan Thiết",
                            SoNguoiToiDa = 4,
                            TenLoai = "Bungalow Biển VIP",
                            TienNghi = "Bungalow riêng, Hồ bơi riêng, View biển 360°",
                            TuKhoa = "biển, beach, phan thiết, vip, bungalow"
                        },
                        new
                        {
                            MaLoai = 10,
                            GiaPhong = 450000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Hà Nội",
                            SoNguoiToiDa = 2,
                            TenLoai = "Phòng Phố Cổ Classic",
                            TienNghi = "View phố cổ, Nội thất gỗ, Máy lạnh, Tivi",
                            TuKhoa = "hà nội, phố cổ, văn hóa, hanoi"
                        },
                        new
                        {
                            MaLoai = 11,
                            GiaPhong = 800000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Hà Nội",
                            SoNguoiToiDa = 2,
                            TenLoai = "Phòng Hồ Gươm View",
                            TienNghi = "View Hồ Gươm, Ban công, Bồn tắm, Minibar",
                            TuKhoa = "hà nội, hồ gươm, view, hanoi"
                        },
                        new
                        {
                            MaLoai = 12,
                            GiaPhong = 1400000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Hà Nội",
                            SoNguoiToiDa = 3,
                            TenLoai = "Phòng Heritage Suite",
                            TienNghi = "Nội thất Đông Dương, Phòng khách rộng, Spa trong phòng",
                            TuKhoa = "hà nội, di sản, heritage, hanoi"
                        },
                        new
                        {
                            MaLoai = 13,
                            GiaPhong = 1000000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Hà Nội",
                            SoNguoiToiDa = 5,
                            TenLoai = "Phòng Gia Đình Hà Nội",
                            TienNghi = "2 Giường đôi, Phòng rộng, View thành phố",
                            TuKhoa = "hà nội, gia đình, hanoi"
                        },
                        new
                        {
                            MaLoai = 14,
                            GiaPhong = 3000000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Hà Nội",
                            SoNguoiToiDa = 4,
                            TenLoai = "Penthouse Royal Hà Nội",
                            TienNghi = "Tầng thượng, View toàn thành phố, Hồ bơi trên mái",
                            TuKhoa = "hà nội, penthouse, royal, vip, hanoi"
                        },
                        new
                        {
                            MaLoai = 15,
                            GiaPhong = 400000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Tây Ninh",
                            SoNguoiToiDa = 2,
                            TenLoai = "Phòng Núi Standard",
                            TienNghi = "View núi Bà Đen, Máy lạnh, Tivi, Không gian thoáng",
                            TuKhoa = "núi, mountain, tây ninh, thiên nhiên"
                        },
                        new
                        {
                            MaLoai = 16,
                            GiaPhong = 700000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Tây Ninh",
                            SoNguoiToiDa = 2,
                            TenLoai = "Phòng Núi Deluxe",
                            TienNghi = "View núi panorama, Ban công rộng, Võng thư giãn, Trà đạo",
                            TuKhoa = "núi, mountain, tây ninh, thư giãn"
                        },
                        new
                        {
                            MaLoai = 17,
                            GiaPhong = 550000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Tây Ninh",
                            SoNguoiToiDa = 2,
                            TenLoai = "Phòng Rừng Xanh Eco",
                            TienNghi = "Eco-lodge, Gần rừng, Xe đạp miễn phí, BBQ",
                            TuKhoa = "núi, mountain, tây ninh, eco, rừng"
                        },
                        new
                        {
                            MaLoai = 18,
                            GiaPhong = 900000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Tây Ninh",
                            SoNguoiToiDa = 5,
                            TenLoai = "Phòng Gia Đình Núi",
                            TienNghi = "2 Phòng ngủ, View núi, Sân vườn rộng, Lò sưởi",
                            TuKhoa = "núi, mountain, tây ninh, gia đình"
                        },
                        new
                        {
                            MaLoai = 19,
                            GiaPhong = 2000000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Tây Ninh",
                            SoNguoiToiDa = 6,
                            TenLoai = "Villa Đỉnh Núi VIP",
                            TienNghi = "Villa riêng trên đồi, Hồ bơi vô cực, View 360° núi rừng",
                            TuKhoa = "núi, mountain, tây ninh, villa, vip"
                        },
                        new
                        {
                            MaLoai = 20,
                            GiaPhong = 650000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Đà Nẵng",
                            SoNguoiToiDa = 2,
                            TenLoai = "Phòng Biển Mỹ Khê",
                            TienNghi = "View biển Mỹ Khê, Máy lạnh, Tivi, Ban công",
                            TuKhoa = "đà nẵng, biển, mỹ khê, beach, miền trung, danang"
                        },
                        new
                        {
                            MaLoai = 21,
                            GiaPhong = 950000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Đà Nẵng",
                            SoNguoiToiDa = 2,
                            TenLoai = "Phòng Sơn Trà View",
                            TienNghi = "View bán đảo Sơn Trà, Bồn tắm, Ban công rộng",
                            TuKhoa = "đà nẵng, sơn trà, view, miền trung, danang"
                        },
                        new
                        {
                            MaLoai = 22,
                            GiaPhong = 1600000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Đà Nẵng",
                            SoNguoiToiDa = 3,
                            TenLoai = "Phòng Suite Hàn River",
                            TienNghi = "View sông Hàn, Phòng khách riêng, Minibar cao cấp",
                            TuKhoa = "đà nẵng, sông hàn, suite, sang trọng, danang"
                        },
                        new
                        {
                            MaLoai = 23,
                            GiaPhong = 1100000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Đà Nẵng",
                            SoNguoiToiDa = 5,
                            TenLoai = "Phòng Gia Đình Đà Nẵng",
                            TienNghi = "2 Phòng ngủ, View biển, Bếp nhỏ, Khu vui chơi",
                            TuKhoa = "đà nẵng, gia đình, rộng, miền trung, danang"
                        },
                        new
                        {
                            MaLoai = 24,
                            GiaPhong = 2800000m,
                            HinhAnh = "default_room.jpg",
                            KhuVuc = "Đà Nẵng",
                            SoNguoiToiDa = 4,
                            TenLoai = "Penthouse Ngũ Hành Sơn",
                            TienNghi = "Tầng cao nhất, View Ngũ Hành Sơn, Hồ bơi riêng",
                            TuKhoa = "đà nẵng, ngũ hành sơn, penthouse, vip, danang"
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<string>("CaLamViec")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Luong")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int?>("MaTK")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayVaoLam")
                        .HasColumnType("date");

                    b.Property<string>("SDT")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNV");

                    b.HasIndex("MaTK")
                        .IsUnique()
                        .HasFilter("[MaTK] IS NOT NULL");

                    b.ToTable("NhanVien");

                    b.HasData(
                        new
                        {
                            MaNV = 1,
                            CaLamViec = "Hành chính",
                            ChucVu = "Quản lý",
                            Luong = 20000000m,
                            MaTK = 1
                        },
                        new
                        {
                            MaNV = 2,
                            CaLamViec = "Ca Sáng",
                            ChucVu = "Lễ tân",
                            Email = "lan@gmail.com",
                            Luong = 8500000m,
                            MaTK = 2,
                            NgayVaoLam = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0901111222"
                        },
                        new
                        {
                            MaNV = 3,
                            CaLamViec = "Ca Chiều",
                            ChucVu = "Lễ tân",
                            Email = "minh@gmail.com",
                            Luong = 8000000m,
                            MaTK = 3,
                            NgayVaoLam = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0902222333"
                        },
                        new
                        {
                            MaNV = 4,
                            CaLamViec = "Ca Sáng",
                            ChucVu = "Thu ngân",
                            Email = "hoa@gmail.com",
                            Luong = 9000000m,
                            MaTK = 4,
                            NgayVaoLam = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0903333444"
                        },
                        new
                        {
                            MaNV = 5,
                            CaLamViec = "Ca Đêm",
                            ChucVu = "Bảo vệ",
                            Email = "hung@gmail.com",
                            Luong = 7500000m,
                            MaTK = 5,
                            NgayVaoLam = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0904444555"
                        },
                        new
                        {
                            MaNV = 6,
                            CaLamViec = "Ca Chiều",
                            ChucVu = "Dọn phòng",
                            Email = "mai@gmail.com",
                            Luong = 7000000m,
                            MaTK = 6,
                            NgayVaoLam = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "0905555666"
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("MaToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaToken"));

                    b.Property<int>("MaTK")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianHetHan")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaToken");

                    b.HasIndex("MaTK");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Phong", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhong");

                    b.HasIndex("MaLoai");

                    b.ToTable("Phong");

                    b.HasData(
                        new
                        {
                            MaPhong = "P101",
                            MaLoai = 1,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "P102",
                            MaLoai = 1,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "P201",
                            MaLoai = 2,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "P202",
                            MaLoai = 2,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "P301",
                            MaLoai = 3,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "P302",
                            MaLoai = 3,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "P401",
                            MaLoai = 4,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "PT101",
                            MaLoai = 5,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "PT102",
                            MaLoai = 6,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "PT103",
                            MaLoai = 7,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "PT104",
                            MaLoai = 8,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "PT105",
                            MaLoai = 9,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "HN101",
                            MaLoai = 10,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "HN102",
                            MaLoai = 11,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "HN103",
                            MaLoai = 12,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "HN104",
                            MaLoai = 13,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "HN105",
                            MaLoai = 14,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "TN101",
                            MaLoai = 15,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "TN102",
                            MaLoai = 16,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "TN103",
                            MaLoai = 17,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "TN104",
                            MaLoai = 18,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "TN105",
                            MaLoai = 19,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "DN101",
                            MaLoai = 20,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "DN102",
                            MaLoai = 21,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "DN103",
                            MaLoai = 22,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "DN104",
                            MaLoai = 23,
                            TrangThai = "Trống"
                        },
                        new
                        {
                            MaPhong = "DN105",
                            MaLoai = 24,
                            TrangThai = "Trống"
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.SuDungDichVu", b =>
                {
                    b.Property<int>("MaSD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSD"));

                    b.Property<int>("MaDP")
                        .HasColumnType("int");

                    b.Property<int>("MaDV")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaSD");

                    b.HasIndex("MaDP");

                    b.HasIndex("MaDV");

                    b.ToTable("SuDungDichVu");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTK"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTK");

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            MaTK = 1,
                            HoTen = "Quản trị viên",
                            MatKhau = "admin",
                            TenDangNhap = "admin",
                            VaiTro = "admin"
                        },
                        new
                        {
                            MaTK = 2,
                            HoTen = "Nguyễn Thị Lân",
                            MatKhau = "lan123",
                            TenDangNhap = "letanlan",
                            VaiTro = "nhanvien"
                        },
                        new
                        {
                            MaTK = 3,
                            HoTen = "Trần Văn Minh",
                            MatKhau = "minh123",
                            TenDangNhap = "minhtrv",
                            VaiTro = "nhanvien"
                        },
                        new
                        {
                            MaTK = 4,
                            HoTen = "Lê Thị Hoa",
                            MatKhau = "hoa123",
                            TenDangNhap = "hoale",
                            VaiTro = "nhanvien"
                        },
                        new
                        {
                            MaTK = 5,
                            HoTen = "Phạm Văn Hùng",
                            MatKhau = "hung123",
                            TenDangNhap = "hungpv",
                            VaiTro = "nhanvien"
                        },
                        new
                        {
                            MaTK = 6,
                            HoTen = "Võ Thị Mai",
                            MatKhau = "mai123",
                            TenDangNhap = "maivo",
                            VaiTro = "nhanvien"
                        });
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.ThuongPhat", b =>
                {
                    b.Property<int>("MaTP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTP"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("date");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("MaTP");

                    b.HasIndex("MaNV");

                    b.ToTable("ThuongPhat");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Voucher", b =>
                {
                    b.Property<int>("MaVC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVC"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("GiaTriToiThieu")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("GioiHanDung")
                        .HasColumnType("int");

                    b.Property<string>("KhuVucApDung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiGiam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MaKH")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLanDaDung")
                        .HasColumnType("int");

                    b.Property<string>("TenVoucher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaVC");

                    b.HasIndex("MaKH");

                    b.ToTable("Voucher");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.ChamCong", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.LichLamViec", "LichLamViec")
                        .WithMany()
                        .HasForeignKey("MaLich")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyKhachSan.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LichLamViec");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DanhGia", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.DatPhong", "DatPhong")
                        .WithMany()
                        .HasForeignKey("MaDP")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyKhachSan.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.LoaiPhong", "LoaiPhong")
                        .WithMany()
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatPhong");

                    b.Navigation("KhachHang");

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DanhGiaNhanVien", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DatPhong", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.HoaDon", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.DatPhong", "DatPhong")
                        .WithMany()
                        .HasForeignKey("MaDP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DatPhong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.KhachHang", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.TaiKhoan", "TaiKhoan")
                        .WithOne()
                        .HasForeignKey("QuanLyKhachSan.Models.KhachHang", "MaTK")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.LichLamViec", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.CaLamViec", "CaLamViec")
                        .WithMany()
                        .HasForeignKey("MaCa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaLamViec");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.NhanVien", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.TaiKhoan", "TaiKhoan")
                        .WithOne()
                        .HasForeignKey("QuanLyKhachSan.Models.NhanVien", "MaTK")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.PasswordResetToken", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Phong", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.LoaiPhong", "LoaiPhong")
                        .WithMany()
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiPhong");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.SuDungDichVu", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.DatPhong", "DatPhong")
                        .WithMany("SuDungDichVus")
                        .HasForeignKey("MaDP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.DichVu", "DichVu")
                        .WithMany()
                        .HasForeignKey("MaDV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatPhong");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.ThuongPhat", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Voucher", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.DatPhong", b =>
                {
                    b.Navigation("SuDungDichVus");
                });
#pragma warning restore 612, 618
        }
    }
}
